### ISSUE TITLE
'gowebly run' not watching for templ file changes

### ISSUE THREAD

**Issue by abuffery** [gowebly/gowebly#38]
Hi,

**What am I expecting:**

I am expecting to execute 'gowebly run' and see in the browser reflected the html changes that I make in the index.templ file

**What happens**

Even if i refresh the browser I do not see the changes reflected, I have to go to the terminal and ctrl-c, rerun gowebly run, go to the browser, refresh the browser, and now I do see the html changes I made in the index.templ file.

**Breakdown of what I am doing:**

1.  gowebly init and change the .gowebly.yml file to have port 3000, echo, templ and tailwindcss
2. gowebly create
3. gowebly run
4. open browser and I see it is working 
5. make small change in html of the default index.tmpl file
6. check to see if the html change is reflected in the browser
7. as the change is not reflected I refresh the browser, the change is still not reflected
8. I ctrl-c gowebly run and I execute again gowebly run
9. check the browser to see if the html changes are reflected, and now they are.

**gowebly doctor output**

=======================================================================================
~$ gowebly doctor
                          _     _       
   __ _  _____      _____| |__ | |_   _ 
  / _` |/ _ \ \ /\ / / _ \ '_ \| | | | |
 | (_| | (_) \ V  V /  __/ |_) | | |_| |
  \__, |\___/ \_/\_/ \___|_.__/|_|\__, |
  |___/ build amazing Go web apps |___/ 
                                                       
○ Generating a report about your system... Please wait!/Users/alejandro/Documents/projects/estimator/.gowebly.yml
                             
Configuration of your system:
                             
 ✓ gowebly version dev
 ✓ go version go1.21.5 darwin/arm64/Users/alejandro/Documents/projects/estimator/.gowebly.yml
 ✓ docker version 24.0.6, build ed223bc
 ✓ docker compose version v2.23.0-desktop.1
 ✓ node v20.9.0
 ✓ templ 0.2.476
           
Next steps:
           
 – If some tools from this list haven't been installed, we strongly recommend installing them manually
 – You can add this information to your issue on GitHub and developers will be able to help you more quickly
                                                                           
‼ To print all commands, just run 'gowebly' without any commands or options
‼ For more information, see https://gowebly.org

=======================================================================================

**.gowebly.yml**

```
# The 'backend' block sets a Go backend options.
# Required to set up.
backend:
  # 'module_name' (string) option can be any name of your Go module (for example, 'github.com/user/project')
  module_name: project
  # 'go_framework' (string) option can be one of the values: 'fiber', 'gin', 'echo', 'chi', 'httprouter', or 'default'
  go_framework: echo
  # 'template_engine' (string) option can be one of the values: 'templ', or 'default'
  template_engine: templ
  # 'port' (int) option can be any port that is not taken up on your system
  port: 3000

  # The 'timeout' block sets a server options.
  # For more information, see https://blog.cloudflare.com/the-complete-guide-to-golang-net-http-timeouts/
  # Required to set up.
  timeout:
    # 'read' (int) option can be any number of seconds, 5 is recommended
    read: 5
    # 'write' (int) option can be any number of seconds, 10 is recommended
    write: 10

# The 'frontend' block sets a frontend options.
# Required to set up.
frontend:
  # 'package_name' (string) option can be any name of your package.json (for example, 'project')
  package_name: project
  # 'css_framework' (string) option can be one of the values: 'tailwindcss', 'unocss', 'daisyui', 'bulma', 'bootstrap' or 'default'
  css_framework: tailwindcss
  # 'runtime_environment' (string) option can be one of the values: 'bun', or 'default'
  runtime_environment: default
  # 'htmx' (string) option can be any existing version
  htmx: latest
  # 'hyperscript' (string) option can be any existing version
  hyperscript: latest
```
